//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileStore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;1.0&quot;
        ///xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;body&gt;
        ///        &lt;h2&gt;
        ///          &lt;xsl:value-of select=&quot;Response/Result/KittenInfo/Name&quot;/&gt; Adopted by the &lt;xsl:value-of select=&quot;Response/Result/Adopter/Name&quot;/&gt;
        ///        &lt;/h2&gt;
        ///      &lt;/body&gt;
        ///    &lt;/html&gt;
        ///  &lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        public static string bwdService {
            get {
                return ResourceManager.GetString("bwdService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Response&gt;
        ///  &lt;Details&gt;
        ///    &lt;StatusCode&gt;0&lt;/StatusCode&gt;
        ///    &lt;Message&gt;AdoptionSuccessful&lt;/Message&gt;
        ///    &lt;MethodName&gt;ProcessAdoption&lt;/MethodName&gt;
        ///    &lt;Caller&gt;
        ///      &lt;Environment&gt;AnimalShelterDevServer&lt;/Environment&gt;
        ///    &lt;/Caller&gt;
        ///  &lt;/Details&gt;
        ///  &lt;Result&gt;
        ///    &lt;Adopter&gt;
        ///      &lt;Name&gt;StenBone Family&lt;/Name&gt;
        ///    &lt;/Adopter&gt;
        ///    &lt;KittenInfo&gt;
        ///      &lt;Name&gt;Rosie Stone&lt;/Name&gt;
        ///      &lt;Fur&gt;grey&lt;/Fur&gt;
        ///      &lt;Attitude&gt;rambunctious&lt;/Attitude&gt;
        ///      &lt;Species&gt;Russian Grey&lt;/Species&gt;
        ///    &lt;/KittenInfo&gt;
        ///  &lt;/Result&gt;
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XMLResponse {
            get {
                return ResourceManager.GetString("XMLResponse", resourceCulture);
            }
        }
    }
}
